### ISSUE TITLE
"Joda date/time type `org.joda.time.DateTime` not supported by default"

### ISSUE THREAD

**Issue by m10x** [tls-attacker/TLS-Scanner#108]
I've received the following error using the latest release (6.1.1):
![image](https://github.com/user-attachments/assets/e406a011-8637-4a6b-be50-40583f13653a)

```
ERROR: ScanReportSerializer - Could not serialize scan report
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Joda date/time type `org.joda.time.DateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-joda" to enable handling (through reference chain: de.rub.nds.tlsscanner.serverscanner.report.ServerReport["results"]->java.util.Collections$UnmodifiableMap["CERTIFICATE_CHAINS"]->de.rub.nds.scanner.core.probe.result.ListResult["value"]->java.util.LinkedList[0]->de.rub.nds.tlsscanner.core.probe.certificate.CertificateChainReport["certificateReportList"]->java.util.LinkedList[0]->de.rub.nds.tlsscanner.core.probe.certificate.CertificateReport["notBefore"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1328)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:184)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1583)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1285)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1081)
	at de.rub.nds.scanner.core.report.ScanReportSerializer.serialize(ScanReportSerializer.java:51)
	at de.rub.nds.scanner.core.execution.Scanner.scan(Scanner.java:197)
	at de.rub.nds.tlsscanner.serverscanner.Main.main(Main.java:44)
```

**Comment by ic0ns** [comment]
@mmaehren I think the main reason these JSON issues are popping up is that we do not have a unit test for this.

**Comment by m10x** [comment]
I'm always using the provided Dockerfile without any modifications. However, I haven't had this error since then. 

Unfortunately I cannot recall in which situation the error was thrown and when it wasn't. I'll try to improve my issues by giving more information. I see that there is a lot of information missing from this issue, especially after two months, especially since I have no memory of it. I'm sorry for this. :/

**Comment by ic0ns** [comment]
Ok funny enough I found a host that triggers it 👍

**Comment by ic0ns** [comment]
This was pretty much the same reason that caused #103 . Its now fixed in version v6.1.6
