### ISSUE TITLE
Run from docker, got error

### ISSUE THREAD

**Issue by y0d4a** [tls-attacker/TLS-Scanner#82]
Hello,

i just try this script and got error:
```
$ sudo docker run -t tlsscanner -connect https://domain.com/
INFO : Main - Performing Scan, this may take some time...
+++Common bugs probe executed
+++Server name indication (SNI) probe executed
+++Compression probe executed
+++Protocol version probe executed
+++Cipher suite order probe executed
+++Client certificate authentication support probe executed
+++Signature Hash Algorithm Order probe executed
+++Record fragmentation probe executed
+++Early CCS probe executed
+++Tokenbinding probe executed
+++HTTP header probe executed
+++Cipher suite probe executed
+++Extensions probe executed
+++EC point formats probe executed
+++Signature and hash algorithm probe executed
+++TLS Fallback SCSV probe executed
+++Hello retry probe executed
+++ESNI probe executed
+++HTTP false start probe executed
+++Certificate probe executed
+++Direct RACCOON probe executed
+++Resumption probe executed
+++Renegotiation probe executed
+++ALPN probe executed
+++Alpaca attack probe executed
+++Heartbleed probe executed
+++Named groups probe executed
Exception in thread "main" java.lang.UnsupportedOperationException: The provided group 'FFDHE2048' is not supported by this method.
        at de.rub.nds.tlsattacker.core.crypto.ec.CurveFactory.getCurve(CurveFactory.java:95)
        at de.rub.nds.tlsscanner.serverscanner.probe.InvalidCurveProbe.adjustConfig(InvalidCurveProbe.java:145)
        at de.rub.nds.tlsscanner.serverscanner.probe.InvalidCurveProbe.adjustConfig(InvalidCurveProbe.java:52)
        at de.rub.nds.scanner.core.execution.ThreadedScanJobExecutor.update(ThreadedScanJobExecutor.java:188)
        at de.rub.nds.scanner.core.execution.ThreadedScanJobExecutor.executeProbesTillNoneCanBeExecuted(ThreadedScanJobExecutor.java:124)
        at de.rub.nds.scanner.core.execution.ThreadedScanJobExecutor.execute(ThreadedScanJobExecutor.java:74)
        at de.rub.nds.tlsscanner.serverscanner.execution.TlsServerScanner.scan(TlsServerScanner.java:298)
        at de.rub.nds.tlsscanner.serverscanner.Main.main(Main.java:45)
```

**Comment by y0d4a** [comment]
hm, nope, i just remove image and pulled again, it is same error

**Comment by mmaehren** [comment]
Did docker show that version 4.2.2 of TLS-Scanner was built?

**Comment by mmaehren** [comment]
Could you please check the output of
```
id=$(docker create tlsscanner)
docker cp $id:/apps/TLS-Server-Scanner.jar - > scanner.tar
docker rm -v $id
tar -xf scanner.tar
unzip -q -c TLS-Server-Scanner.jar META-INF/MANIFEST.MF | grep "Implementation-Version"
```
The script extracts the version information from the Jar used by the docker image.

**Comment by y0d4a** [comment]
yeah, not latest :/
Implementation-Version: 4.2.1

is there option to update or to uninstall/install?

**Comment by mmaehren** [comment]
You could try `docker image rm -f tlsscanner:latest` and subsequently re-pull the git repo and build the docker image again. Does the .pom file in your cloned repo show version 4.2.2? I'd expect docker to overwrite an image upon a new build if something has changed.

**Comment by y0d4a** [comment]
that did not help, i did must remove cache files from /var/lib/docker...

now is working with new version, thank you!
